/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Zennova
 */
import javax.swing.JOptionPane;


public class MainWindow extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        gameButton.addActionListener(e -> {
        new TopUpWindow().setVisible(true);
        this.dispose();
        });

        pulsaButton.addActionListener(e -> {
            new PulsaWindow().setVisible(true);
            this.dispose();
        });
        comingSoonButton.addActionListener(e -> {
        JOptionPane.showMessageDialog(
            this,
            "Pilihan ini belum tersedia. Pantau terus Mambo Store!",
            "Coming Soon",
            JOptionPane.INFORMATION_MESSAGE
            );
        });
        
        addHoverEffect(gameButton);
        addHoverEffect(pulsaButton);
        addHoverEffect(comingSoonButton);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundMain = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        Pilihan = new javax.swing.JLabel();
        gameButton = new javax.swing.JButton();
        pulsaButton = new javax.swing.JButton();
        comingSoonButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BackgroundMain.setBackground(new java.awt.Color(102, 255, 204));

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.setFont(new java.awt.Font("MingLiU-ExtB", 1, 18)); // NOI18N
        Title.setText("Mambo Store");

        Description.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        Description.setText("Tempat top up Game dan Pulsa termurah, tercepat, dan terpercaya di Indonesia. Proses Otomatis gak sampai 1 menit.");

        Pilihan.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        Pilihan.setText("Mau apa?");

        gameButton.setBackground(new java.awt.Color(153, 255, 255));
        gameButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gameButton.setText("Top up Game");
        gameButton.addActionListener(this::gameButtonActionPerformed);

        pulsaButton.setBackground(new java.awt.Color(204, 153, 255));
        pulsaButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pulsaButton.setText("Pulsa & E-Money");

        comingSoonButton.setBackground(new java.awt.Color(255, 51, 102));
        comingSoonButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comingSoonButton.setText("Coming Soon");

        javax.swing.GroupLayout BackgroundMainLayout = new javax.swing.GroupLayout(BackgroundMain);
        BackgroundMain.setLayout(BackgroundMainLayout);
        BackgroundMainLayout.setHorizontalGroup(
            BackgroundMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BackgroundMainLayout.createSequentialGroup()
                        .addComponent(Pilihan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(339, 339, 339))
            .addGroup(BackgroundMainLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(gameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pulsaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comingSoonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundMainLayout.setVerticalGroup(
            BackgroundMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pilihan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comingSoonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pulsaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameButtonActionPerformed

    private void addHoverEffect(javax.swing.JButton button) {
        java.awt.Color originalColor = button.getBackground();
        java.awt.Color hoverColor = originalColor.brighter();

        button.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                button.setBackground(hoverColor);
                button.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(java.awt.Color.WHITE, 2),
                    javax.swing.BorderFactory.createEmptyBorder(4, 4, 8, 4) // padding bawah lebih → kesan naik
                ));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                button.setBackground(originalColor);
                button.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundMain;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Pilihan;
    private javax.swing.JLabel Title;
    private javax.swing.JButton comingSoonButton;
    private javax.swing.JButton gameButton;
    private javax.swing.JButton pulsaButton;
    // End of variables declaration//GEN-END:variables
}
