/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Zennova
 */
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;


public class MainWindow extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());
    
/**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        gameButton.addActionListener(e -> {
        new TopUpWindow().setVisible(true);
        this.dispose();
        });

        pulsaButton.addActionListener(e -> {
            new PulsaWindow().setVisible(true);
            this.dispose();
        });
        comingSoonButton.addActionListener(e -> {
        JOptionPane.showMessageDialog(
            this,
            "Pilihan ini belum tersedia. Pantau terus Mambo Store!",
            "Coming Soon",
            JOptionPane.INFORMATION_MESSAGE
            );
        });
        
        applyFuturisticLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        Pilihan = new javax.swing.JLabel();
        gameButton = new javax.swing.JButton();
        pulsaButton = new javax.swing.JButton();
        comingSoonButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.setFont(new java.awt.Font("MingLiU-ExtB", 1, 18)); // NOI18N
        Title.setText("Mambo Store");
        Title.setBounds(0, 0, 130, 24);
        getContentPane().add(Title);

        Description.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        Description.setText("Tempat top up Game dan Pulsa termurah, tercepat, dan terpercaya di Indonesia. Proses Otomatis gak sampai 1 menit.");
        Description.setBounds(10, 350, 760, 24);
        getContentPane().add(Description);

        Pilihan.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        Pilihan.setText("Mau apa?");
        Pilihan.setBounds(80, 370, 100, 24);
        getContentPane().add(Pilihan);

        gameButton.setBackground(new java.awt.Color(177, 139, 255));
        gameButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gameButton.setText("Top up Game");
        gameButton.addActionListener(this::gameButtonActionPerformed);
        gameButton.setBounds(140, 390, 230, 60);
        getContentPane().add(gameButton);

        pulsaButton.setBackground(new java.awt.Color(207, 188, 255));
        pulsaButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pulsaButton.setText("Pulsa & E-Money");
        pulsaButton.setBounds(390, 390, 230, 60);
        getContentPane().add(pulsaButton);

        comingSoonButton.setBackground(new java.awt.Color(116, 57, 232));
        comingSoonButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comingSoonButton.setText("Coming Soon");
        comingSoonButton.setBounds(640, 390, 220, 60);
        getContentPane().add(comingSoonButton);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bannerMain.png"))); // NOI18N
        background.setBounds(0, 20, 940, 330);
        getContentPane().add(background);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameButtonActionPerformed

    private void applyFuturisticLayout() {
        FuturisticUI.BackgroundPanel root = FuturisticUI.background("/assets/bannerMain.png");
        root.setLayout(new BorderLayout(0, 18));
        root.setBorder(new EmptyBorder(20, 24, 24, 24));

        FuturisticUI.BannerPanel hero = FuturisticUI.banner("/assets/bannerMain.png", 350);
        root.add(hero, BorderLayout.NORTH);

        FuturisticUI.GlassPanel menuPanel = FuturisticUI.glass(new BorderLayout(18, 18));

        JPanel textStack = new JPanel();
        textStack.setOpaque(false);
        textStack.setLayout(new BoxLayout(textStack, BoxLayout.Y_AXIS));

        FuturisticUI.title(Title, "Mambo Store", 31);
        Title.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

        FuturisticUI.body(Description,
            "<html><div style='width:780px'>Tempat top up game, pulsa, dan e-money yang cepat, aman, dan siap dipakai kapan saja.</div></html>",
            15);
        Description.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

        FuturisticUI.body(Pilihan, "Pilih layanan", 16);
        Pilihan.setForeground(FuturisticUI.VIOLET);
        Pilihan.setFont(Pilihan.getFont().deriveFont(java.awt.Font.BOLD, 16f));
        Pilihan.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

        textStack.add(Title);
        textStack.add(Box.createVerticalStrut(6));
        textStack.add(Description);
        textStack.add(Box.createVerticalStrut(16));
        textStack.add(Pilihan);

        JPanel buttonGrid = new JPanel(new GridLayout(1, 3, 18, 0));
        buttonGrid.setOpaque(false);

        FuturisticUI.styleCommandButton(gameButton, FuturisticUI.VIOLET, new Color(172, 132, 255));
        FuturisticUI.styleCommandButton(pulsaButton, new Color(132, 79, 242), new Color(207, 188, 255));
        FuturisticUI.styleCommandButton(comingSoonButton, new Color(92, 62, 168), new Color(167, 132, 238));

        buttonGrid.add(gameButton);
        buttonGrid.add(pulsaButton);
        buttonGrid.add(comingSoonButton);

        menuPanel.add(textStack, BorderLayout.NORTH);
        menuPanel.add(buttonGrid, BorderLayout.CENTER);

        root.add(menuPanel, BorderLayout.CENTER);
        setContentPane(root);
        FuturisticUI.prepareFrame(this, "Mambo Store", 1060, 720);
        revalidate();
        repaint();
    }

    private void addHoverEffect(javax.swing.JButton button) {
        java.awt.Color originalColor = button.getBackground();
        java.awt.Color hoverColor = originalColor.brighter();

        button.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                button.setBackground(hoverColor);
                button.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(java.awt.Color.WHITE, 2),
                    javax.swing.BorderFactory.createEmptyBorder(4, 4, 8, 4) // padding bawah lebih → kesan naik
                ));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                button.setBackground(originalColor);
                button.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Pilihan;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel background;
    private javax.swing.JButton comingSoonButton;
    private javax.swing.JButton gameButton;
    private javax.swing.JButton pulsaButton;
    // End of variables declaration//GEN-END:variables
}
