/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Zennova
 */
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

public class TopUpWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TopUpWindow.class.getName());

    /**
     * Creates new form TopUpWindow
     */
    public TopUpWindow() {
        initComponents();
        
        // ===== 1. TOGGLE BUTTON: hanya bisa pilih 1 =====
        javax.swing.ButtonGroup gameGroup = new javax.swing.ButtonGroup();
        gameGroup.add(valorantButton);
        gameGroup.add(hsrButton);
        gameGroup.add(mlbbButton);
        gameGroup.add(wuwaButton);

        // ===== 2. BACK BUTTON =====
        backButton.addActionListener(e -> {
            new MainWindow().setVisible(true);
            this.dispose();
        });

        // ===== 3. KONFIRMASI BUTTON =====
        confirmButton.addActionListener(e -> {

            // Cek game dipilih
            String selectedGame = "";
            String currency = "";
            double rate = 0;

            if (valorantButton.isSelected()) {
                selectedGame = "Valorant";
                currency = "Valorant Points (VP)";
                rate = 1000.0 / 108625.0;   // VP per Rupiah
            } else if (hsrButton.isSelected()) {
                selectedGame = "Honkai: Star Rail";
                currency = "Oneiric Shard";
                rate = 60.0 / 16000.0;
            } else if (mlbbButton.isSelected()) {
                selectedGame = "Mobile Legends: Bang Bang";
                currency = "Diamond";
                rate = 110.0 / 30235.0;
            } else if (wuwaButton.isSelected()) {
                selectedGame = "Wuthering Waves";
                currency = "Lunites";
                rate = 60.0 / 14922.0;
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Pilih game terlebih dahulu!",
                    "Peringatan",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Cek nominal diisi
            String nominalText = jTextField1.getText().trim();
            if (nominalText.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Masukkan nominal top up!",
                    "Peringatan",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            double nominal;
            try {
                nominal = Double.parseDouble(nominalText);
            } catch (NumberFormatException ex) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Nominal harus berupa angka!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            long estimasi = Math.round(nominal * rate);

            // Pop up minta ID game
            String gameId = javax.swing.JOptionPane.showInputDialog(
                this,
                "Game       : " + selectedGame + "\n" +
                "Nominal    : Rp " + String.format("%,.0f", nominal) + "\n" +
                "Estimasi   : " + estimasi + " " + currency + "\n\n" +
                "Masukkan ID " + selectedGame + " kamu:",
                "Konfirmasi Top Up",
                javax.swing.JOptionPane.PLAIN_MESSAGE
            );

            // Kalau user isi ID dan klik OK
            if (gameId != null && !gameId.trim().isEmpty()) {
                String ringkasan = "Game   : " + selectedGame + "\n" +
                                   "ID     : " + gameId.trim() + "\n" +
                                   "Nominal: Rp " + String.format("%,.0f", nominal) + "\n" +
                                   "Estimasi: " + estimasi + " " + currency + "\n";
                PaymentDialog.show(this, ringkasan, nominal);
            }
        });

        applyFuturisticLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundGame = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valorantButton = new javax.swing.JToggleButton();
        hsrButton = new javax.swing.JToggleButton();
        mlbbButton = new javax.swing.JToggleButton();
        wuwaButton = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackgroundGame.setBackground(new java.awt.Color(244, 239, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Top Up Game, Mambo Store");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Untuk saat ini, berikut adalah pilihan Game yang tersedia:");

        valorantButton.setBackground(new java.awt.Color(124, 57, 226));
        valorantButton.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N
        valorantButton.setText("Valorant");
        valorantButton.addActionListener(this::valorantButtonActionPerformed);

        hsrButton.setBackground(new java.awt.Color(104, 75, 203));
        hsrButton.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N
        hsrButton.setForeground(new java.awt.Color(255, 255, 255));
        hsrButton.setText("Honkai: Star Rail");

        mlbbButton.setBackground(new java.awt.Color(145, 84, 243));
        mlbbButton.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N
        mlbbButton.setText("Mobile Legends: Bang Bang");

        wuwaButton.setBackground(new java.awt.Color(84, 62, 158));
        wuwaButton.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N
        wuwaButton.setText("Wuthering Waves");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Silahkan masukkan nominal top up yang anda inginkan (Rupiah):");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        confirmButton.setBackground(new java.awt.Color(116, 57, 232));
        confirmButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmButton.setText("Konfirmasi");

        backButton.setBackground(new java.awt.Color(82, 61, 151));
        backButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backButton.setText("Kembali");
        backButton.addActionListener(this::backButtonActionPerformed);

        javax.swing.GroupLayout BackgroundGameLayout = new javax.swing.GroupLayout(BackgroundGame);
        BackgroundGame.setLayout(BackgroundGameLayout);
        BackgroundGameLayout.setHorizontalGroup(
            BackgroundGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundGameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundGameLayout.createSequentialGroup()
                        .addGroup(BackgroundGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundGameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(BackgroundGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(BackgroundGameLayout.createSequentialGroup()
                                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundGameLayout.createSequentialGroup()
                                .addComponent(valorantButton)
                                .addGap(18, 18, 18)
                                .addComponent(hsrButton)
                                .addGap(18, 18, 18)
                                .addComponent(mlbbButton)
                                .addGap(18, 18, 18)
                                .addComponent(wuwaButton)))))
                .addContainerGap())
        );
        BackgroundGameLayout.setVerticalGroup(
            BackgroundGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(BackgroundGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorantButton)
                    .addComponent(hsrButton)
                    .addComponent(mlbbButton)
                    .addComponent(wuwaButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BackgroundGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorantButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorantButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void applyFuturisticLayout() {
        FuturisticUI.BackgroundPanel root = FuturisticUI.background("/assets/bgGameViolet.png");
        root.setLayout(new BorderLayout(0, 18));
        root.setBorder(new EmptyBorder(18, 22, 22, 22));

        root.add(FuturisticUI.banner("/assets/bannerMain.png", 260), BorderLayout.NORTH);

        FuturisticUI.GlassPanel panel = FuturisticUI.glass(new BorderLayout(18, 18));

        JPanel header = new JPanel();
        header.setOpaque(false);
        header.setLayout(new BoxLayout(header, BoxLayout.Y_AXIS));

        FuturisticUI.title(jLabel1, "Top Up Game", 30);
        jLabel1.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
        FuturisticUI.body(jLabel2, "Pilih game tujuan, lalu masukkan nominal top up dalam Rupiah.", 15);
        jLabel2.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

        header.add(jLabel1);
        header.add(Box.createVerticalStrut(6));
        header.add(jLabel2);

        JPanel gameGrid = new JPanel(new GridLayout(2, 2, 14, 14));
        gameGrid.setOpaque(false);

        FuturisticUI.styleToggleButton(valorantButton, new Color(124, 57, 226), new Color(196, 170, 255));
        FuturisticUI.styleToggleButton(hsrButton, new Color(104, 75, 203), new Color(180, 149, 255));
        FuturisticUI.styleToggleButton(mlbbButton, new Color(145, 84, 243), new Color(212, 195, 255));
        FuturisticUI.styleToggleButton(wuwaButton, new Color(84, 62, 158), new Color(177, 145, 244));

        gameGrid.add(valorantButton);
        gameGrid.add(hsrButton);
        gameGrid.add(mlbbButton);
        gameGrid.add(wuwaButton);

        JPanel formStack = new JPanel();
        formStack.setOpaque(false);
        formStack.setLayout(new BoxLayout(formStack, BoxLayout.Y_AXIS));

        FuturisticUI.body(jLabel3, "Nominal top up (Rupiah)", 15);
        jLabel3.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
        FuturisticUI.styleTextField(jTextField1);
        jTextField1.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 54));
        jTextField1.setPreferredSize(new java.awt.Dimension(10, 54));

        JPanel actions = new JPanel(new GridLayout(1, 2, 14, 0));
        actions.setOpaque(false);
        FuturisticUI.styleCommandButton(confirmButton, FuturisticUI.VIOLET, new Color(177, 139, 255));
        FuturisticUI.styleCommandButton(backButton, new Color(82, 61, 151), new Color(151, 108, 232));
        actions.add(confirmButton);
        actions.add(backButton);

        formStack.add(jLabel3);
        formStack.add(Box.createVerticalStrut(10));
        formStack.add(jTextField1);
        formStack.add(Box.createVerticalStrut(14));
        formStack.add(actions);

        panel.add(header, BorderLayout.NORTH);
        panel.add(gameGrid, BorderLayout.CENTER);
        panel.add(formStack, BorderLayout.SOUTH);

        root.add(panel, BorderLayout.CENTER);
        setContentPane(root);
        FuturisticUI.prepareFrame(this, "Mambo Store - Top Up Game", 1040, 740);
        revalidate();
        repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TopUpWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundGame;
    private javax.swing.JButton backButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JToggleButton hsrButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton mlbbButton;
    private javax.swing.JToggleButton valorantButton;
    private javax.swing.JToggleButton wuwaButton;
    // End of variables declaration//GEN-END:variables
}
